executable=subash.sh

output = ../jobs/outs/$(Item)_$(L).out
error = ../jobs/errs/$(Item)_$(L).err
log = ../jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour="short"

L=1
ch=0.01
args=$(Item) $(L) $(ch)
queue from seq 0.01 0.05 3.0|

L=2
ch=0.01
args=$(Item) $(L) $(ch)
queue from seq 0.01 0.05 3.0|

L=3
ch=0.01
args=$(Item) $(L) $(ch)
queue from seq 0.01 0.05 3.0|

L=4
ch=0.01
args=$(Item) $(L) $(ch)
queue from seq 0.01 0.05 3.0|
