executable=subash.sh 
L=1
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=2
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=3
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=4
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=5
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=6
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=7
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=8
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=9
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=10
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=11
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=12
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=13
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
executable=subash.sh 
L=14
output = jobs/outs/$(Item)_$(L).out
error = jobs/errs/$(Item)_$(L).err
log = jobs/logs/$(Item)_$(L).log
request_cpus = 1
+flavour='medium'

args=$(Item) $(L)
queue from seq 1.36 0.01 1.5| 
 
 
